'use client'

import { Editor } from '@tinymce/tinymce-react'
import { useQuery } from '@tanstack/react-query'
import { ArrowDown, ArrowLeft, ArrowUp, ImagePlus, Loader2, X } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useEffect, useMemo, useState, useTransition } from 'react'
import { toast } from 'sonner'

import type { MediaItem } from '@/@types/types-media'
import type { PortfolioStatus } from '@/@types/types-portfolio'
import { savePortfolioProjectAction } from '@/actions/portfolio-actions'
import { ChipsInput } from '@/components/chips-input'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { getPortfolioProject, listPortfolioCategories } from '@/http/portfolio'
import { listMedia } from '@/http/list-media'

export default function PortfolioForm({ projectId }: { projectId?: string }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const projectQuery = useQuery({ queryKey: ['portfolio-project', projectId], queryFn: () => getPortfolioProject(projectId!), enabled: !!projectId }); const categories = useQuery({ queryKey: ['portfolio-categories'], queryFn: listPortfolioCategories })
  const project = projectQuery.data?.project
  const [title, setTitle] = useState(''); const [slug, setSlug] = useState(''); const [summary, setSummary] = useState(''); const [html, setHtml] = useState(''); const [status, setStatus] = useState<PortfolioStatus>('DRAFT'); const [featured, setFeatured] = useState(false); const [displayOrder, setDisplayOrder] = useState(0); const [location, setLocation] = useState(''); const [architects, setArchitects] = useState<string[]>([]); const [area, setArea] = useState(''); const [year, setYear] = useState(''); const [clientName, setClientName] = useState(''); const [services, setServices] = useState<string[]>([]); const [seoTitle, setSeoTitle] = useState(''); const [metaDescription, setMetaDescription] = useState(''); const [categoryIds, setCategoryIds] = useState<string[]>([]); const [gallery, setGallery] = useState<MediaItem[]>([])
  useEffect(() => { if (!project) return; setTitle(project.title); setSlug(project.slug); setSummary(project.summary); setHtml(project.content?.html || ''); setStatus(project.status); setFeatured(project.featured); setDisplayOrder(project.displayOrder); setLocation(project.location || ''); setArchitects(project.architects); setArea(project.areaSquareMeters?.toString() || ''); setYear(project.completionYear?.toString() || ''); setClientName(project.clientName || ''); setServices(project.servicesProvided); setSeoTitle(project.seoTitle || ''); setMetaDescription(project.metaDescription || ''); setCategoryIds(project.categories.map((item) => item.id)); setGallery(project.gallery as MediaItem[]) }, [project])
  const cover = gallery[0]
  const selectedCategories = useMemo(() => new Set(categoryIds), [categoryIds])
  const submit = () => startTransition(async () => { if (!title.trim() || !summary.trim() || !html.trim()) { toast.error('Preencha título, resumo e conteúdo.'); return } if (!gallery.length) { toast.error('Selecione ao menos uma imagem.'); return } const result = await savePortfolioProjectAction(projectId || null, { title, slug: slug || undefined, summary, content: { format: 'html', version: 1, html }, status, featured, displayOrder, location: location || null, architects, areaSquareMeters: area ? Number(area) : null, completionYear: year ? Number(year) : null, clientName: clientName || null, servicesProvided: services, seoTitle: seoTitle || null, metaDescription: metaDescription || null, coverId: cover.id, categoryIds, galleryMediaIds: gallery.map((item) => item.id), ...(project ? { expectedVersion: project.version } : {}) }); if (!result.success) { toast.error(result.message); return } toast.success('Projeto salvo com sucesso.'); router.push('/portfolio') })
  if (projectId && projectQuery.isLoading) return <div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin" /></div>
  return <div className="space-y-6"><div className="flex items-center gap-4"><Button asChild variant="outline" size="icon"><Link href="/portfolio"><ArrowLeft className="size-4" /></Link></Button><div><h1 className="text-3xl font-bold">{projectId ? 'Editar projeto' : 'Novo projeto'}</h1><p className="text-muted-foreground">Monte a apresentação editorial do projeto.</p></div></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]"><div className="space-y-6"><Card><CardHeader><CardTitle>Conteúdo</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Título"><Input value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="Slug"><Input value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="Gerado automaticamente quando vazio" /></Field><Field label="Resumo"><Textarea value={summary} maxLength={500} onChange={(event) => setSummary(event.target.value)} /></Field><Field label="Corpo completo"><Editor apiKey="gvivvvi7xjncbwzkuxvfq7pnts47bdem1n3gjvrfazfvu2vh" value={html} onEditorChange={setHtml} init={{ height: 560, menubar: true, plugins: ['autolink','lists','link','image','table','code','preview','fullscreen','wordcount'], toolbar: 'undo redo | blocks | bold italic | alignleft aligncenter alignright | bullist numlist | link image table | code fullscreen', branding: false }} /></Field></CardContent></Card>
      <Card><CardHeader><CardTitle>Galeria</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">A primeira imagem será a capa. Use as setas para definir a ordem.</p><GalleryPicker selected={gallery} onChange={setGallery} /><div className="grid gap-3 sm:grid-cols-2">{gallery.map((media, index) => <div key={media.id} className="flex gap-3 rounded-lg border p-2"><div className="relative h-20 w-28 shrink-0 overflow-hidden rounded-md"><Image src={media.url} alt={media.alt || `Imagem ${index + 1}`} fill className="object-cover" sizes="112px" /></div><div className="flex min-w-0 flex-1 flex-col justify-between"><p className="truncate text-sm font-medium">{index === 0 ? 'Capa · ' : ''}{media.title || media.alt || `Imagem ${index + 1}`}</p><div className="flex gap-1"><Button type="button" size="icon" variant="ghost" disabled={index === 0} onClick={() => setGallery(move(gallery, index, index - 1))}><ArrowUp className="size-4" /></Button><Button type="button" size="icon" variant="ghost" disabled={index === gallery.length - 1} onClick={() => setGallery(move(gallery, index, index + 1))}><ArrowDown className="size-4" /></Button><Button type="button" size="icon" variant="ghost" onClick={() => setGallery(gallery.filter((item) => item.id !== media.id))}><X className="size-4" /></Button></div></div></div>)}</div></CardContent></Card></div>
      <div className="space-y-6"><Card><CardHeader><CardTitle>Publicação</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Status"><Select value={status} onValueChange={(value: PortfolioStatus) => setStatus(value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="DRAFT">Rascunho</SelectItem><SelectItem value="PUBLISHED">Publicado</SelectItem></SelectContent></Select></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={featured} onChange={(event) => setFeatured(event.target.checked)} className="size-4 accent-primary" />Projeto em destaque</label><Field label="Ordem"><Input type="number" value={displayOrder} onChange={(event) => setDisplayOrder(Number(event.target.value))} /></Field></CardContent></Card>
      <Card><CardHeader><CardTitle>Ficha técnica</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Localidade"><Input value={location} onChange={(event) => setLocation(event.target.value)} /></Field><ChipsInput label="Arquitetos" name="architects" defaultValues={architects} onChange={setArchitects} placeholder="Digite e pressione Enter" /><div className="grid grid-cols-2 gap-3"><Field label="Área (m²)"><Input type="number" min="0" step="0.01" value={area} onChange={(event) => setArea(event.target.value)} /></Field><Field label="Ano"><Input type="number" value={year} onChange={(event) => setYear(event.target.value)} /></Field></div><Field label="Cliente (opcional)"><Input value={clientName} onChange={(event) => setClientName(event.target.value)} /></Field><ChipsInput label="Serviços realizados" name="services" defaultValues={services} onChange={setServices} placeholder="Digite e pressione Enter" /></CardContent></Card>
      <Card><CardHeader><CardTitle>Categorias</CardTitle></CardHeader><CardContent className="space-y-3">{categories.data?.items.map((item) => <label key={item.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selectedCategories.has(item.id)} onChange={(event) => setCategoryIds((current) => event.target.checked ? [...current, item.id] : current.filter((id) => id !== item.id))} className="size-4 accent-primary" />{item.name}</label>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>SEO</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Título SEO"><Input maxLength={60} value={seoTitle} onChange={(event) => setSeoTitle(event.target.value)} /></Field><Field label="Meta description"><Textarea maxLength={160} value={metaDescription} onChange={(event) => setMetaDescription(event.target.value)} /></Field></CardContent></Card><Button className="w-full" size="lg" onClick={submit} disabled={pending}>{pending && <Loader2 className="animate-spin" />}Salvar projeto</Button></div></div>
  </div>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div> }
function move<T>(items: T[], from: number, to: number) { const next = [...items]; const [item] = next.splice(from, 1); next.splice(to, 0, item); return next }
function GalleryPicker({ selected, onChange }: { selected: MediaItem[]; onChange: (items: MediaItem[]) => void }) { const [open, setOpen] = useState(false); const media = useQuery({ queryKey: ['media', 'portfolio-picker'], queryFn: () => listMedia({ page: 1, perPage: 60 }), enabled: open }); const selectedIds = new Set(selected.map((item) => item.id)); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button type="button" variant="outline"><ImagePlus className="size-4" />Selecionar imagens</Button></DialogTrigger><DialogContent className="max-h-[85dvh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>Galeria do projeto</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">{media.data?.items.map((item) => <button key={item.id} type="button" className={`relative aspect-video overflow-hidden rounded-md border-2 ${selectedIds.has(item.id) ? 'border-primary' : 'border-transparent'}`} onClick={() => onChange(selectedIds.has(item.id) ? selected.filter((mediaItem) => mediaItem.id !== item.id) : [...selected, item])}><Image src={item.url} alt={item.alt || 'Mídia'} fill className="object-cover" sizes="25vw" /></button>)}</div><DialogFooter><Button type="button" onClick={() => setOpen(false)}>Concluir ({selected.length})</Button></DialogFooter></DialogContent></Dialog> }
