'use client'

import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Edit, FolderTree, Loader2, MoreVertical, Search, Trash2 } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState, useTransition } from 'react'
import { toast } from 'sonner'

import type { PortfolioCategory } from '@/@types/types-portfolio'
import { createPortfolioCategoryAction, deletePortfolioCategoryAction, deletePortfolioProjectAction, updatePortfolioCategoryAction } from '@/actions/portfolio-actions'
import { DeleteDialog } from '@/components/delete-dialog'
import { EmptyState, ErrorState } from '@/components/page-state'
import { StatCard } from '@/components/stats-card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { listPortfolioCategories, listPortfolioProjects } from '@/http/portfolio'

export default function PortfolioManager() {
  const queryClient = useQueryClient(); const [search, setSearch] = useState(''); const [debounced, setDebounced] = useState(''); const [status, setStatus] = useState('all'); const [page, setPage] = useState(1); const [deleteId, setDeleteId] = useState<string | null>(null); const [category, setCategory] = useState<PortfolioCategory | null>(null); const [categoryOpen, setCategoryOpen] = useState(false); const [categoryDelete, setCategoryDelete] = useState<PortfolioCategory | null>(null); const [pending, startTransition] = useTransition()
  useEffect(() => { const timer = window.setTimeout(() => { setDebounced(search); setPage(1) }, 350); return () => window.clearTimeout(timer) }, [search])
  const projects = useQuery({ queryKey: ['portfolio-projects', page, debounced, status], queryFn: () => listPortfolioProjects({ page, search: debounced || undefined, status: status === 'all' ? undefined : status }) })
  const categories = useQuery({ queryKey: ['portfolio-categories'], queryFn: listPortfolioCategories })
  const refresh = () => Promise.all([queryClient.invalidateQueries({ queryKey: ['portfolio-projects'] }), queryClient.invalidateQueries({ queryKey: ['portfolio-categories'] })])
  const removeProject = () => deleteId && startTransition(async () => { const result = await deletePortfolioProjectAction(deleteId); if (!result.success) { toast.error(result.message); return } setDeleteId(null); await refresh(); toast.success('Projeto excluído.') })
  const saveCategory = (form: FormData) => startTransition(async () => { const data = { name: String(form.get('name') || ''), description: String(form.get('description') || ''), displayOrder: Number(form.get('displayOrder') || 0) }; const result = category ? await updatePortfolioCategoryAction(category.id, data) : await createPortfolioCategoryAction(data); if (!result.success) { toast.error(result.message); return } setCategoryOpen(false); setCategory(null); await refresh(); toast.success('Categoria salva.') })
  const removeCategory = () => categoryDelete && startTransition(async () => { const result = await deletePortfolioCategoryAction(categoryDelete.id); if (!result.success) { toast.error(result.message); return } setCategoryDelete(null); await refresh(); toast.success('Categoria excluída.') })
  return <Tabs defaultValue="projects" className="space-y-5"><TabsList><TabsTrigger value="projects">Projetos</TabsTrigger><TabsTrigger value="categories">Categorias</TabsTrigger></TabsList><TabsContent value="projects" className="space-y-5">
    <div className="grid gap-4 md:grid-cols-3"><StatCard title="Total" value={projects.data?.stats?.total ?? '—'} /><StatCard title="Publicados" value={projects.data?.stats?.published ?? '—'} /><StatCard title="Rascunhos" value={projects.data?.stats?.drafts ?? '—'} /></div>
    <Card><CardContent className="flex flex-col gap-4 pt-6 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-10" placeholder="Buscar projeto ou local" value={search} onChange={(event) => setSearch(event.target.value)} /></div><Select value={status} onValueChange={(value) => { setStatus(value); setPage(1) }}><SelectTrigger className="sm:w-48"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todos os status</SelectItem><SelectItem value="PUBLISHED">Publicados</SelectItem><SelectItem value="DRAFT">Rascunhos</SelectItem></SelectContent></Select></CardContent></Card>
    {projects.isError ? <ErrorState title="Falha ao carregar portfólio" description="Tente novamente." onRetry={() => projects.refetch()} /> : !projects.isLoading && !projects.data?.items.length ? <EmptyState title="Nenhum projeto encontrado" description="Crie o primeiro projeto do portfólio." /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.isLoading ? Array.from({ length: 6 }).map((_, index) => <Card key={index} className="h-72 animate-pulse bg-muted" />) : projects.data?.items.map((project) => <Card key={project.id} className="overflow-hidden"><div className="relative aspect-video bg-muted">{project.gallery[0] ? <Image src={project.gallery[0].url} alt={project.gallery[0].alt || project.title} fill className="object-cover" sizes="(min-width:1280px) 33vw, 50vw" /> : null}<Badge className="absolute left-3 top-3" variant={project.status === 'PUBLISHED' ? 'default' : 'secondary'}>{project.status === 'PUBLISHED' ? 'Publicado' : 'Rascunho'}</Badge></div><CardContent className="space-y-3 p-4"><div className="flex items-start justify-between gap-2"><div><h2 className="font-semibold">{project.title}</h2><p className="text-sm text-muted-foreground">{project.location || 'Local não informado'} · {project.galleryCount} imagem(ns)</p></div><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost"><MoreVertical className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild><Link href={`/portfolio/edit/${project.id}`}><Edit className="size-4" />Editar</Link></DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem variant="destructive" onClick={() => setDeleteId(project.id)}><Trash2 className="size-4" />Excluir</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></CardContent></Card>)}</div>}
    {projects.data && <div className="flex justify-end gap-2"><Button variant="outline" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Anterior</Button><Button variant="outline" disabled={page >= projects.data.meta.totalPages} onClick={() => setPage((value) => value + 1)}>Próxima</Button></div>}
  </TabsContent><TabsContent value="categories" className="space-y-4"><div className="flex justify-end"><Button onClick={() => { setCategory(null); setCategoryOpen(true) }}><FolderTree className="size-4" />Nova categoria</Button></div><Card><CardContent className="divide-y p-0">{categories.data?.items.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 p-4"><div><p className="font-medium">{item.name}</p><p className="text-sm text-muted-foreground">{item.description || 'Sem descrição'} · {item._count?.projects || 0} projeto(s)</p></div><div className="flex gap-2"><Button size="icon" variant="ghost" onClick={() => { setCategory(item); setCategoryOpen(true) }}><Edit className="size-4" /></Button><Button size="icon" variant="ghost" onClick={() => setCategoryDelete(item)}><Trash2 className="size-4" /></Button></div></div>)}</CardContent></Card></TabsContent>
    <DeleteDialog open={!!deleteId} onOpenChange={(open) => !open && setDeleteId(null)} onConfirm={removeProject} isPending={pending} title="Excluir projeto" description="O projeto será removido, mas as mídias compartilhadas serão preservadas." />
    <DeleteDialog open={!!categoryDelete} onOpenChange={(open) => !open && setCategoryDelete(null)} onConfirm={removeCategory} isPending={pending} title="Excluir categoria" description="Categorias vinculadas a projetos não podem ser excluídas." />
    <Dialog open={categoryOpen} onOpenChange={setCategoryOpen}><DialogContent><DialogHeader><DialogTitle>{category ? 'Editar categoria' : 'Nova categoria'}</DialogTitle><DialogDescription>Organize os projetos exibidos no site.</DialogDescription></DialogHeader><form action={saveCategory} className="space-y-4"><div><Label htmlFor="category-name">Nome</Label><Input id="category-name" name="name" defaultValue={category?.name} required /></div><div><Label htmlFor="category-description">Descrição</Label><Input id="category-description" name="description" defaultValue={category?.description || ''} /></div><div><Label htmlFor="category-order">Ordem</Label><Input id="category-order" name="displayOrder" type="number" defaultValue={category?.displayOrder || 0} /></div><DialogFooter><Button type="submit" disabled={pending}>{pending && <Loader2 className="animate-spin" />}Salvar</Button></DialogFooter></form></DialogContent></Dialog>
  </Tabs>
}
