import type { Metadata } from 'next'
import { Roboto, Roboto_Mono } from 'next/font/google'
// @ts-ignore: allow side-effect CSS import without type declarations
import './globals.css'
import Providers from './providers'
import Header from '@/components/header'

const robotoSans = Roboto({
  variable: '--font-roboto-sans',
  subsets: ['latin']
})

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Certifica - Dashboard',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased h-full`}
        cz-shortcut-listen="true"
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
